name: grocery_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.4
  shared_preferences: ^2.0.20
  get_it: ^7.2.0
  go_router: ^6.5.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  hive: ^2.2.3
  hive_generator: ^2.0.0
  cloud_firestore: ^4.5.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

